name: Nasazení na Sandbox
on:
  release:
    types:
      - released
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Naklonování repozitáře
        uses: actions/checkout@v4
      - name: Ensure data directory exists
        run: mkdir -p data
      - name: Create empty database file if it doesn't exist
        run: |
          if [ -f "data/gamebook.db" ]; then
            echo "Using existing database file"
          else
            echo "Creating empty database file to ensure directory permissions"
            touch data/gamebook.db
            chmod 666 data/gamebook.db
          fi
      - name: Přihlášení se k Sandboxu
        uses: docker/login-action@v3
        with:
          username: ignored
          password: ${{ secrets.SANDBOX_BUILD_TOKEN }}
          registry: registry.pslib.cloud
      - name: Nainstalování Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Sestavení a nahrání kontejnerového obrazu
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./GamebookTest1.Server/Dockerfile
          push: true
          tags: registry.pslib.cloud/sandbox/app-40:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
